PRODUCT_VERSION_MAJOR = 1
PRODUCT_VERSION_MINOR = 0

ifeq ($(MYTHIC_VERSION_APPEND_TIME_OF_DAY),true)
    MYTHIC_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
    MYTHIC_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

# Set MYTHIC_BUILDTYPE from the env RELEASE_TYPE, for jenkins compat

ifndef MYTHIC_BUILDTYPE
    ifdef RELEASE_TYPE
        # Starting with "MYTHIC_" is optional
        RELEASE_TYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^MYTHIC_||g')
        MYTHIC_BUILDTYPE := $(RELEASE_TYPE)
    endif
endif

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(MYTHIC_BUILDTYPE)),)
    MYTHIC_BUILDTYPE := UNOFFICIAL
    MYTHIC_EXTRAVERSION :=
endif

ifeq ($(MYTHIC_BUILDTYPE), UNOFFICIAL)
    ifneq ($(TARGET_UNOFFICIAL_BUILD_ID),)
        MYTHIC_EXTRAVERSION := -$(TARGET_UNOFFICIAL_BUILD_ID)
    endif
endif

MYTHIC_VERSION_SUFFIX := $(MYTHIC_BUILD_DATE)-$(MYTHIC_BUILDTYPE)$(MYTHIC_EXTRAVERSION)-$(MYTHIC_BUILD)

# Internal version
MYTHIC_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(MYTHIC_VERSION_SUFFIX)

# Display version
MYTHIC_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(MYTHIC_VERSION_SUFFIX)
